import { createStep } from "@mastra/core/workflows";
import { z } from "zod";
import * as fs from "fs/promises";
import * as path from "path";

export const reviewResearchStep = createStep({
  id: "review-research",
  description: "Writes research findings to a file for human review",
  inputSchema: z.object({
    personaDescription: z.string(),
    industry: z.string(),
    context: z.string(),
    topic: z.string(),
    questionCount: z.number(),
    interviewFocus: z.string(),
    researchContext: z.string(),
  }),
  outputSchema: z.object({
    personaDescription: z.string(),
    industry: z.string(),
    context: z.string(),
    topic: z.string(),
    questionCount: z.number(),
    interviewFocus: z.string(),
    researchContext: z.string(),
  }),
  execute: async ({ inputData }) => {
    const {
      personaDescription,
      industry,
      context,
      topic,
      questionCount,
      interviewFocus,
      researchContext,
    } = inputData;

    console.log("\n\n=== REVIEW STEP ===");

    // Define report path
    const reportPath = path.join(process.cwd(), "research-report.md");

    const reportContent = `
# Research Report: ${personaDescription}
**Industry:** ${industry}
**Date:** ${new Date().toISOString()}

---

## Context
${context}

## Research Findings (Generated by Agent)

${researchContext}

---
*End of Report*
    `.trim();

    // Write file to disk
    await fs.writeFile(reportPath, reportContent, "utf-8");

    console.log(`✅ Research report written to: ${reportPath}`);
    console.log("⚠️  PLEASE REVIEW THIS FILE BEFORE CONTINUING.");
    console.log(
      "(In a fully interactive mode, the workflow would pause here.)"
    );

    return {
      personaDescription,
      industry,
      context,
      topic,
      questionCount,
      interviewFocus,
      researchContext,
    };
  },
});
